### PR TITLE
Introduce aggregated memory allocation, using dlmalloc

### PR DESCRIPTION
**Pull request by zellerh**
ORCA does a lot of memory allocations, and each allocation is fairly expensive,
recording additional information and doing checks (e.g. OOM).

We would like to use the GPDB memory allocators by default (change the default
for optimizer_use_gpdb_allocators to on), to prevent ORCA from crashing when
we run out of memory (OOM). However, with the current way of doing things, doing
so would add around 10 % performance overhead to ORCA.

As a solution, we are adding an "aggregation layer" to the ORCA CMemoryPoolTracker
to speed up memory allocations. This will allow us to use GPDB memory allocators
while at the same time speeding up ORCA overall.

Basically, this aggregation layer manages memory and combines many (usually small)
memory requests into larger requests that are then satisfied by the GPDB memory
allocators. The code to do this comes from open source, a memory allocation algorithm
called dlmalloc, developed by Doug Lea that is released to the public domain and that
is also used by the GNU runtime library.

See http://gee.cs.oswego.edu/dl/html/malloc.html and
http://gee.cs.oswego.edu/pub/misc/malloc-2.8.3.c

On our development machine (MacOS), we saw 15 % to 40 % improvement in optimization
time and about a 50 % reduction in the allocated memory. This is using a retail build.

We made this change in the CMemoryPoolTracker class, since it is the one that is used
almost everywhere as the top-most memory pool object. Other classes like CMemoryPoolAlloc
are used in lower layers to do the actual allocation of memory.

What did we change in dlmalloc?

- We eliminated global variables in dlmalloc and put a struct describing the state
  of the dlmalloc system into each CMemoryPoolTracker object. This struct is called
  malloc_state.
- This means that each CMemoryPoolTracker object aggregates memory independently.
- Since ORCA does not specify a memory pool when deleting memory, we need to store
  a pointer back to the malloc_state in every allocated chunk of memory.
- We tried to simplify the dlmalloc code by deleting many unused features.
- The dlmalloc method requests memory in larger chunks from the lower layers
  (CMemoryPoolAlloc and ultimately the GPDB memory allocators). These chunks are
  called "segments". To avoid waste and having too many segments, the segment size
  increases exponentially, starting at 32 KB and increasing in factors of 8, up to
  64 MB.

The code is written to allow a mix of aggregated and non-aggregated requests, even
in the same CMemoryPoolTracker. When deallocating, we recognize which type of allocation
we used by a marker (CMemoryPool::AllocHeader::m_zero_marker).

For array allocations, we store the number of array elements in the allocated chunk,
to be able to call the correct destructors when deallocating the memory.

We also made the parameters that pass file name and line numbers to the memory allocation
routines conditional, they are now only passed when GPOS_DEBUG is defined. Finding memory
leaks will now be slightly different: The initial step will be the same, when running
an MDP file in gporca_test, a list of memory leaks will be generated, but the file name
and line numbers point to the aggregation layer in CMemoryPoolTracker. To find the actual
objects that are leaked, run gporca_test with the following option to turn off aggregated
allocation: -T 105. In psql, use this guc:

set optimizer_enable_aggregated_memory_allocation = off;

This feature will be enabled by default in 6X and Master. It will be off in 5X and there
is no guc to turn it on in 5X.

When parsing DXL, a memory pool is created before the trace flags are set. In that case,
we need to update the memory pool to disable aggregated memory, once the traceflag is
set.

Misc. changes:

- Avoid using an AutoMemoryPool in one instance, use the default memory pool of CTask::Self()
  instead, this should avoid allocating unnecessary extra segments.

- Avoid exception when loading search strategy.

Co-authored-by: Ashuka Xue <axue@pivotal.io>
Co-authored-by: Chris Hajas <chajas@pivotal.io>
Co-authored-by: Hans Zeller <hzeller@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
>  We would like to use the GPDB memory allocators by default (change the default
for optimizer_use_gpdb_allocators to on), to prevent ORCA from crashing when
we run out of memory (OOM). However, with the current way of doing things, doing
so would add around 10 % performance overhead to ORCA.

Where does that overhead come from? palloc/pfree isn't all that slow in general, is there some ORCA specific overhead if it's used in ORCA?

**Comment by hlinnaka** [comment]
Is there a particular query or test suite you've been using for the performance tests?

**Comment by hlinnaka** [comment]
>      

The GPDB allocators are not inefficient, the issue is that ORCA makes many, many allocations (specifically many small allocations), and this overhead adds up to a significant amount in some cases (~10% of total optimization time from our measurements in the TPC-DS suite). The memory allocation overhead in ORCA was even more significant.

Hmm. This patch doesn't reduce the number of calls to the underlying "alloc" function. Is the effect here that dlmalloc() is just so much faster than glibc's malloc()?

> In ORCA, we don't end up calling palloc, we end up calling gp_malloc, which directly calls malloc.

Looking at all the things that gp_malloc() does, calling palloc() would probably be faster.

**Comment by zellerh** [comment]
Thanks for the great feedback so far! We rebased the code on the newer [dlmalloc-2.8.6](http://gee.cs.oswego.edu/pub/misc/malloc-2.8.6.c) that comes with the [Creative Commons CC0 1.0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by zellerh** [comment]
@hlinnaka, without this patch, every ORCA memory allocation descends about 11 stack frames deep (assuming we use GPDB allocators), until it reaches GLIBC malloc(). Descending all these stack frames for every allocation ends up being extremely expensive. On the way, we do various checks and add three different structures as overhead. This patch changes that, we use the new dlmalloc in the third stack frame, before adding any overhead, or doing any accounting checks. We descend the entire 11 frames only when we allocate larger amounts of memory, managed by dlmalloc. In other words, we no longer call malloc for every memory allocation, instead malloc is only called to allocate the larger segments, and dlmalloc handles the smaller allocations. This reduces the number of times we call the GPDB memory allocators by several orders of magnitude, but still retains the useful checks when allocating larger chunks.

As far as we know, the goal is to use the gpdb::OptimizerAlloc and gp_malloc methods, since those methods have some useful OOM checks and also tell GPDB how much memory ORCA is using, so it can enforce policies. With this new model, the overhead caused by the GPDB allocators is negligible.

@chrishajas and @zellerh

**Comment by hlinnaka** [comment]
On 29/08/2019 02:28, Hans Zeller wrote:
> @hlinnaka <https://github.com/hlinnaka>, without this patch, every ORCA 
> memory allocation descends about 11 stack frames deep (assuming we use 
> GPDB allocators), until it reaches GLIBC malloc(). Descending all these 
> stack frames for every allocation ends up being extremely expensive. On 
> the way, we do various checks and add three different structures as 
> overhead. This patch changes that, we use the new dlmalloc in the third 
> stack frame, before adding any overhead, or doing any accounting checks. 
> We descend the entire 11 frames only when we allocate larger amounts of 
> memory, managed by dlmalloc. In other words, we no longer call malloc 
> for every memory allocation, instead malloc is only called to allocate 
> the larger segments, and dlmalloc handles the smaller allocations. This 
> reduces the number of times we call the GPDB memory allocators by 
> several orders of magnitude, but still retains the useful checks when 
> allocating larger chunks.

Hmm. I'm seeing stack traces like this:

(gdb) bt
#0  __GI___libc_malloc (bytes=bytes@entry=128) at malloc.c:3025
#1  0x0000564e1dc261a9 in malloc_and_store_metadata (size=120) at 
memprot.c:336
#2  gp_malloc_internal (requested_size=120) at memprot.c:382
#3  gp_malloc (sz=sz@entry=120) at memprot.c:413
#4  0x0000564e1dc27736 in Ext_OptimizerAlloc (size=size@entry=120) at 
ext_alloc.c:45
#5  0x0000564e1dcf4e2e in gpdb::OptimizerAlloc (size=120) at 
gpdbwrappers.cpp:3200
#6  0x00007fb9dc4276ec in gpos::CMemoryPoolTracker::Allocate(unsigned 
int, char const*, unsigned int) () from 
/home/heikki/gpdb/orca-install/lib/libgpos.so.3
#7  0x00007fb9dc425a83 in gpos::CMemoryPool::NewImpl(unsigned long, char 
const*, unsigned int, gpos::CMemoryPool::EAllocationType) () from 
/home/heikki/gpdb/orca-install/lib/libgpos.so.3
#8  0x0000564e1dcda824 in operator new (line=193, 
filename=0x564e1dea0da0 
"/home/heikki/gpdb/orca-install/include/gpos/common/CHashMap.h", 
mp=<optimized out>, size=48)
     at /home/heikki/gpdb/orca-install/include/gpos/memory/CMemoryPool.h:405
#9  gpos::CHashMap<unsigned int, gpdxl::CCTEListEntry, 
&gpos::HashValue<unsigned int>, &gpos::Equals<unsigned int>, 
&gpos::CleanupDelete<unsigned int>, 
&gpos::CleanupRelease<gpdxl::CCTEListEntry> >::CHashMap (num_chains=127, 
mp=0x564e1fe5d7b8, this=0x564e1fee93d8) at 
/home/heikki/gpdb/orca-install/include/gpos/common/CHashMap.h:193
#10 gpdxl::CTranslatorQueryToDXL::CTranslatorQueryToDXL 
(this=0x564e1fecc308, context=<optimized out>, md_accessor=<optimized 
out>, var_colid_mapping=<optimized out>, query=0x564e1ff33ae8,
     query_level=0, is_top_query_dml=false, query_level_to_cte_map=0x0) 
at CTranslatorQueryToDXL.cpp:177
#11 0x0000564e1dcdadca in 
gpdxl::CTranslatorQueryToDXL::QueryToDXLInstance 
(mp=mp@entry=0x564e1fe5d7b8, 
md_accessor=md_accessor@entry=0x7ffd9b3a5460, query=0x564e1ff33ae8)
     at /home/heikki/gpdb/orca-install/include/gpos/memory/CMemoryPool.h:405
#12 0x0000564e1dcec4cb in COptTasks::OptimizeTask (ptr=0x7ffd9b3a5bd0) 
at COptTasks.cpp:711
#13 0x00007fb9dc42a1b8 in gpos::CTask::Execute() () from 
/home/heikki/gpdb/orca-install/lib/libgpos.so.3
#14 0x00007fb9dc42af68 in gpos::CWorker::Execute(gpos::CTask*) () from 
/home/heikki/gpdb/orca-install/lib/libgpos.so.3
#15 0x00007fb9dc42999d in gpos::CAutoTaskProxy::Execute(gpos::CTask*) () 
from /home/heikki/gpdb/orca-install/lib/libgpos.so.3
#16 0x00007fb9dc41f2cf in gpos_exec () from 
/home/heikki/gpdb/orca-install/lib/libgpos.so.3
#17 0x0000564e1dceab5f in COptTasks::Execute (func=0x564e1dcec330 
<COptTasks::OptimizeTask(void*)>, func_arg=0x7ffd9b3a5bd0) at 
COptTasks.cpp:300
#18 0x0000564e1dceb8f8 in COptTasks::GPOPTOptimizedPlan 
(query=query@entry=0x564e1ff33ae8, 
gpopt_context=gpopt_context@entry=0x7ffd9b3a5bd0) at COptTasks.cpp:938
#19 0x0000564e1dced7bd in CGPOptimizer::GPOPTOptimizedPlan 
(query=0x564e1ff33ae8, had_unexpected_failure=0x7ffd9b3a5c3f) at 
CGPOptimizer.cpp:52
#20 0x0000564e1da5f270 in optimize_query 
(parse=parse@entry=0x564e1fbe4dd0, boundParams=boundParams@entry=0x0) at 
orca.c:142

If I'm reading this patch correctly, the aggregation happens at the 
CMemoryPoolTracker() level. It replaces stack frames 0-4 with the one 
call to dlmalloc(). So this boils down to "OptimizerAlloc is slow". When 
not using the GPDB allocators, this patch shouldn't have much effect, 
assuming glibc malloc() is roughly on par with dlmalloc(). Is that correct?

Can we make OptimizerAlloc faster? We could easily replace the call to 
gp_malloc() with MemoryContextAlloc(), so that the we would use the 
standard GPDB/Postgres AllocSet allocator. I think that would be faster 
than gp_malloc().

Even AllocSetAlloc() is pretty slow in GPDB compared to PostgreSQL, 
though, because we've added a bunch of memory accounting bookkeeping to 
the critical paths. We should clear that up, because it's slowing down 
the whole system, independently from ORCA.

Approaching this from the other direction in the stack, why do we have 
separate CMemoryPool and CMemoryPoolTracker objects? Could we merge them 
into one?

PS. I ran a quick test with "perf", to get a profile of where CPU time 
is spent, with a small query ("explain select * from onek where unique1 
between 10 and 20"). The allocators indeed show up high in the profile, 
but there's another elephant in the room too:

Samples: 12K of event 'cycles:ppp', Event count (approx.): 7805479413
   Children      Self  Command     Shared Object           Symbol
+   70.50%     0.02%  postmaster  postgres                [.] 
COptTasks::OptimizeTask 
                                                       ◆
+   59.11%     0.01%  postmaster  libxerces-c-3.2.so      [.] 
xercesc_3_2::XMLScanner::scanDocument 
                                                       ▒
+   58.78%     0.01%  postmaster  libxerces-c-3.2.so      [.] 
xercesc_3_2::IGXMLScanner::scanDocument 
                                                       ▒
+   57.78%     0.01%  postmaster  postgres                [.] 
non-virtual thunk to 
xercesc_3_2::DefaultHandler::fatalError(xercesc_3_2::SAXParseException 
const&)                            ▒
+   57.74%     0.01%  postmaster  libxerces-c-3.2.so      [.] 
xercesc_3_2::XMLScanner::scanProlog 
                                                       ▒
+   57.66%     0.01%  postmaster  libxerces-c-3.2.so      [.] 
xercesc_3_2::SAX2XMLReaderImpl::error 
                                                       ▒
+   57.64%     0.00%  postmaster  libxerces-c-3.2.so      [.] 
xercesc_3_2::XMLScanner::emitError 
                                                       ▒
+   56.52%     0.00%  postmaster  libnaucrates.so.3.65.3  [.] 
gpdxl::CDXLUtils::GetParseHandlerForDXLFile 
                                                       ▒
+   55.87%     0.00%  postmaster  libgpos.so.3.65.3       [.] 
gpos::CException::Raise 
                                                       ▒
+   52.15%     0.01%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::COptimizer::PdxlnOptimize 
                                                       ▒
+   33.49%     0.01%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::COptimizer::PexprOptimize 
                                                       ▒
+   25.67%     1.31%  postmaster  libgpos.so.3.65.3       [.] 
gpos::CMemoryPool::NewImpl 
                                                       ▒
+   24.74%     0.01%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CEngine::Optimize 
                                                       ▒
+   24.59%     2.70%  postmaster  libgpos.so.3.65.3       [.] 
gpos::CMemoryPoolTracker::Allocate 
                                                       ▒
+   23.84%     0.00%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CScheduler::Run 
                                                       ▒
+   23.84%     0.02%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CScheduler::ExecuteJobs 
                                                       ▒
+   22.94%     0.02%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CQueryContext::PqcGenerate 
                                                       ▒
+   22.70%     0.00%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CQueryContext::CQueryContext 
                                                       ▒
+   22.53%     0.02%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CExpressionPreprocessor::PexprPreprocess 
                                                       ▒
+   21.03%     1.37%  postmaster  postgres                [.] 
gpdb::OptimizerAlloc 
                                                       ▒
+   16.44%     0.81%  postmaster  postgres                [.] gp_malloc 
 
                                             ▒
+   14.74%     0.09%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CExpression::PdpDerive 
                                                       ▒
+   14.49%     6.10%  postmaster  libc-2.28.so            [.] malloc 
 
                                             ▒
+   13.64%     1.13%  postmaster  postgres                [.] 
gpdb::OptimizerFree 
                                                       ▒
+   13.27%     2.21%  postmaster  libgpos.so.3.65.3       [.] 
gpos::CMemoryPoolTracker::Free 
                                                       ▒
+   10.97%     0.00%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CExpressionPreprocessor::PexprAddPredicatesFromConstraints 
                                                       ▒
+   10.86%     0.02%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CScheduler::FExecute 
                                                       ▒
+   10.13%     0.02%  postmaster  libgpopt.so.3.65.3      [.] 
gpopt::CDrvdPropRelational::Derive 
                                                       ▒

56.52% of the time was spent in 
gpdxl::CDXLUtils::GetParseHandlerForDXLFile(). Huh? Why are we trying to 
read a file, when optimizing query? Turns out it's coming from this, in 
OptimizeTask function:

	// load search strategy
	CSearchStageArray *search_strategy_arr = LoadSearchStrategy(mp, 
optimizer_search_strategy_path);

We try to load a "search stratgy" from a file called "default" in the 
data directory. On every, single, query.

- Heikki

**Comment by hlinnaka** [comment]
I spent some time experimenting on this memory allocation thing. At a high-level, I don't like the idea of  adding yet another allocator layer. The problem is that we're walking up and down the stack, and doing other work, on every allocation. Adding yet another layer to solve that problem seems backwards.

IMHO we should teach ORCA to use GPDB MemoryContexts, and palloc/pfree, with as few layers on top of that as possible. I hacked together a little prototype to do that. It seems to work for basic queries, but I haven't tried running the regression tests or more complex stuff:

https://github.com/hlinnaka/gpdb/tree/orca-malloc-optimizations
https://github.com/hlinnaka/gporca/tree/malloc-optimizations

The fundamental changes here are:

- Change GPORCA  CMemoryPool stuff so that they are not nested. A memory pool no longer has an "underlying memory pool". CMemoryPoolTracker and CMemoryPoolStack now call malloc() directly, and CMemoryPoolAlloc is removed altogether. (On second thoughts, these changes are not 100% necessarily, given the next point, but seems like a good simplification anyway)
- Allow replacing the memory pool implementation altogether. Currently, GPDB passes custom malloc/free() functions to GPORCA. But with these changes, GPDB provides a complete replacement for CMemoryPoolTracker/Stack. In the replacement implementation, there's a 1-to-1 mapping between CMemoryPools and GPDB MemoryContexts, and CMemoryPool->Allocate/Free use MemoryContextAlloc and pfree().

- On that branch, I also reverted all the memory accounting changes to aset.c. That speeds up palloc/pree() significantly. And breaks memory accounting, of course, but as far as ORCA is concerned, I think MemoryContexts are much better for tracking memory usage anyway. Memory accounting lumps all memory used by ORCA together, but with one MemoryContext per ORCA memory pool, we could get more detailed statistics.

This is just a quick prototype, and a lot of debugging and statistics stuff is broken, but it gives a good idea on what kind of performance we can get from this. Instead of adding new stuff to make it faster, let's remove stuff.

- Heikki

**Comment by zellerh** [comment]
Thanks very much for your comments and for the prototype, @hlinnaka! We like it a lot and would like to use it instead of our dlmalloc approach. We tried it and @chrishajas found that it performs as well as our code, when using GPDB allocators, using some complex queries like TPC-DS query 72.

As you pointed out, it's better to optimize memory allocations on the gpdb side and avoid adding a new layer in ORCA.

> On that branch, I also reverted all the memory accounting changes to aset.c. That speeds up palloc/pree() significantly. And breaks memory accounting, of course, but as far as ORCA is concerned, I think MemoryContexts are much better for tracking memory usage anyway. 

Could you clarify what the consequences are of that change and whether there are additional things we need to be aware of with respect to GPDB?

Our plan is to close this PR in the next few days and to move forward with a new PR, based on your changes.

@ashuka24, @chrishajas and @zellerh

**Comment by chrishajas** [comment]
>  Allow replacing the memory pool implementation altogether. Currently, GPDB passes custom malloc/free() functions to GPORCA. But with these changes, GPDB provides a complete replacement for CMemoryPoolTracker/Stack. In the replacement implementation, there's a 1-to-1 mapping between CMemoryPools and GPDB MemoryContexts, and CMemoryPool->Allocate/Free use MemoryContextAlloc and pfree().

@hlinnaka Is there any performance/debugging/other advantage to having a 1-to-1 mapping between the ORCA CMemoryPools and GPDB Memory Contexts vs having many CMemoryPools in a single GPDB Memory Context?

**Comment by hlinnaka** [comment]
On 04/09/2019 21:16, Chris Hajas wrote:
>     Allow replacing the memory pool implementation altogether.
>     Currently, GPDB passes custom malloc/free() functions to GPORCA. But
>     with these changes, GPDB provides a complete replacement for
>     CMemoryPoolTracker/Stack. In the replacement implementation, there's
>     a 1-to-1 mapping between CMemoryPools and GPDB MemoryContexts, and
>     CMemoryPool->Allocate/Free use MemoryContextAlloc and pfree().
> 
> @hlinnaka <https://github.com/hlinnaka> Is there any 
> performance/debugging/other advantage to having a 1-to-1 mapping between 
> the ORCA CMemoryPools and GPDB Memory Contexts vs having many 
> CMemoryPools in a single GPDB Memory Context?

I'm not sure; how does ORCA utilize memory pools? It seems like it might 
be useful to get list of ORCA memory pools on out of memory, like you 
get for Postgres memory contexts. But I'm not sure how fine-grained the 
memory pools are in ORCA, or if there's some better way to get the same 
information from ORCA.

- Heikki

**Comment by chrishajas** [comment]
> I'm not sure; how does ORCA utilize memory pools? It seems like it might be useful to get list of ORCA memory pools on out of memory, like you get for Postgres memory contexts. But I'm not sure how fine-grained the memory pools are in ORCA, or if there's some better way to get the same information from ORCA. - Heikki

Currently, parts of ORCA create memory pools very liberally. For some relatively simple queries, we may generate thousands or tens of thousands of very short-lived memory pools (which we're very likely abusing and can be improved). Would that be an issue for GPDB memory contexts?

Using the existing memory pool tracker framework, we do get insight into memory leaks/utilization in debug mode, but we've only been using that for debugging in-house (and with your implementation, that remains intact).

**Pull request closed without merging**
