### PR TITLE
Adding concourse pipeline address

### PR DESCRIPTION
**Pull request by xinzweb**
Fix url for the concourse.io and bosh.io

### CODE REVIEW

**Comment by xinzweb** [comment]
@vraghavan78 @d @hsyuan

**Comment by hsyuan** [comment]
LGTM

**Comment by xinzweb** [comment]
Thanks @hsyuan. @d  @oarap and @vraghavan78?

**Comment by vraghavan78** [comment]
+1

**Comment by d** [comment]
Our pipelines are behind auth, so it's essentially not publicly visible. Should we put them in README before we tackle the issue of opening up our CI?

**Comment by xinzweb** [comment]
I was thinking we have opened our CI. Anyway, we need to fix up the `https` issue. Let me close this PR, and redo it when we have the pipeline story fixed.

**Pull request closed without merging**
