### PR TITLE
Adding a How to contribute section to the README

### PR DESCRIPTION
**Pull request by jpatel-pivotal**
Adding **How to Contribute** section to the README to make it easy for developers to send us PRs.

### CODE REVIEW

**Comment by jpatel-pivotal** [comment]
@vraghavan78 @oarap @dhanashreek89 @khannaekta @bhuvnesh2703 

Please review and provide feedback.

**Comment by schubert** [comment]
I think since the intent is to follow GPDB's own contributor policy I think it would be good to also reference and link to it so it's clear that is the overall intent as the contribution guide there is a bit more comprehensive but you likely don't need to repeat all the same info.

Keeping some clear, concise instructions for your own repo is still valuable though as its less mental overhead to comprehend for someone new.

**Comment by jpatel-pivotal** [comment]
Good point @schubert. Added reference to it.

**Comment by d** [comment]
Please add `[ci skip]` in commit message to avoid triggering another (wrong) publishing on Github release

**Comment by schubert** [comment]
+ @khuddlefish for consideration of gpbackup.

**Pull request merged**
