### PR TITLE
Remove unused Slab memory pool and Slab cache stuff

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Comment by hsyuan** [comment]
You forgot to bump the version...

**Comment by hlinnaka** [comment]
On 06/21/2017 06:27 PM, Haisheng Yuan wrote:
> You forgot to bump the version...

I'm happy to just leave it in master until the next version bump, 
there's no hurry in getting this into use by any consumers of ORCA.

- Heikki

**Comment by hsyuan** [comment]
I don't mind leave it either. But someone is going to yell at me. :)
Because the CI will generate binary and override the previous version.
Anyway, I stopped the CI, wait for next commit to bump the version.

**Comment by hlinnaka** [comment]
On 06/21/2017 06:34 PM, Haisheng Yuan wrote:
> I don't mind leave it either. But someone is going to yell at me. :)

I'm OK with that as well ;-)

> Because the CI will generate binary and override the previous version.
> Anyway, I stopped the CI, wait for next commit to bump the version.

Well that's a bizarre way to set up CI. Huh!?

- Heikki

**Comment by hawqtoolsmiths** [comment]
On Wed, Jun 21, 2017 at 11:36 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 06/21/2017 06:34 PM, Haisheng Yuan wrote:
> > I don't mind leave it either. But someone is going to yell at me. :)
>
> I'm OK with that as well ;-)
>
> > Because the CI will generate binary and override the previous version.
> > Anyway, I stopped the CI, wait for next commit to bump the version.
>
> Well that's a bizarre way to set up CI. Huh!?


Agreed. Seems like that pipeline should adopt some sort of arrangement like
the gpdb_master pipeline where no matter what - you get a unique version
out of a commit so even if it's not semver-correct to bump the version
number you don't smash the artifact accidentally. We have solutions for
this problem, it's a matter of the gporca pipeline adopting them.

**Comment by d** [comment]
> I'm happy to just leave it in master until the next version bump,

This project unfortunately has adopted a bad practice from Postgres where the version number is in the repository. That means every push that will lead to new artifacts needs to bump the version.

**Pull request closed without merging**
