### PR TITLE
[#123259241] fix array paritition tests

### PR DESCRIPTION
**Pull request by cramja**
This adds the traceflag for `ArrayConstraints` and fixes the resulting plans. Changes to plans are mainly in `PrintableFilter` element (OR->Array), but also in some `Filter` elements (OR->Array).

Also the constant's ordering in `ScalarArray` element (now sorted).

### CODE REVIEW

**Comment by cramja** [comment]
@oarap @d @hsyuan @vraghavan78 Should be a simple PR to review. Added Array traceflag and changed some minidump tests to reflect the changes/

**Comment by vraghavan78** [comment]
+1

**Comment by cramja** [comment]
[ctest_diff.py](https://gist.github.com/cramja/f34f34aad39e179211178375d7299591)

**Comment by hsyuan** [comment]
LGTM

**Pull request merged**
