### PR TITLE
Remove unused "communicator" code.

### PR DESCRIPTION
**Pull request by hlinnaka**
None of this was used. The reason to purge it now is that I want to remove
the CSocket code from gpos, and this was the only thing that depended on
that.

### CODE REVIEW

**Comment by hlinnaka** [comment]
see also https://github.com/greenplum-db/gpos/pull/31

**Comment by d** [comment]
When you merge, can you bump the ORCA version number?

**Comment by d** [comment]
Same goes to the GPOS changes

**Comment by hlinnaka** [comment]
Ok, bumped version number and pushed.

**Pull request closed without merging**
