### PR TITLE
Using INT_MAX instead of ULONG_MAX to avoid Xerces issue

### PR DESCRIPTION
**Pull request by xinzweb**
@vraghavan78 @oarap @d

### CODE REVIEW

**Comment by hsyuan** [comment]
+1

**Comment by vraghavan78** [comment]
+1

**Comment by danielgustafsson** [comment]
Out of curiosity, what was the Xerces issue?

**Comment by xinzweb** [comment]
Xerces `XMLString` class has a `parseInt()` function, which only returned a signed int. However, in GPORCA code, we use it to return a ULONG. In this case, we set default value of ULONG_MAX out of range of INT. Hence, this fix is to lower the default value to INT_MAX instead of ULONG_MAX. Thanks.

**Comment by danielgustafsson** [comment]
> On 12 Apr 2016, at 20:11, Xin Zhang <notifications@github.com> wrote:
> 
> Xerces XMLString class has a parseInt() function, which only returned a signed int. However, in GPORCA code, we use it to return a ULONG. In this case, we set default value of ULONG_MAX out of range of INT. Hence, this fix is to lower the default value to INT_MAX instead of ULONG_MAX. Thanks.

Thanks a lot for clarifying!

**Pull request closed without merging**
