### PR TITLE
Reduce hash collisions when processing a large number of columns

### PR DESCRIPTION
**Pull request by chrishajas**
Our hashing function, which is dependent on the size of the hash table,
was hashing to the same bucket during constant expression evaluation.
Instead, modify the hash table size to be an odd number to significantly
reduce hash collisions. In the future, we should modify our hashing
function to not be influenced by the hash table size, but that will be a
larger effort.

This reduces optimization time by 50%+ for some queries. In one case,
this reduced optimization time from 25s to 9s on my laptop.

Partially addresses https://github.com/greenplum-db/gporca/issues/523
Authored-by: Chris Hajas <chajas@pivotal.io>

### CODE REVIEW

**Comment by sambitesh** [comment]
LGTM, are there any more even sized Hashmaps in ORCA left?

**Comment by chrishajas** [comment]
> LGTM, are there any more even sized Hashmaps in ORCA left?

I don't believe so, unless we create a custom sized hashmap based on the number of columns. I can also just add logic when initializing the hashmap to always create an odd-sized hashmap. That way we don't accidentally hit this issue again.

**Comment by hsyuan** [comment]
Memo bucket size is 50000.
see https://github.com/greenplum-db/gporca/blob/master/libgpopt/src/search/CMemo.cpp#L36

**Comment by wuboy0307** [comment]
After update PQO to 3.72.0. The issue still exists. Are you going to enhance this more on next version or is there any workaround to overcome this issue? 
I have a table which contains 700up columns. The performance is really bad. 

Thanks a lot...

**Comment by zellerh** [comment]
Hi @wuboy0307, would you be able to provide a test case to reproduce your issue?

**Comment by wuboy0307** [comment]
> Hi @wuboy0307, would you be able to provide a test case to reproduce your issue?

Hi @zellerh ,
Please take a look
https://gist.github.com/wuboy0307/1f314bd4293be5653378652f21bd5472

I create a table with 100000 rows, and the table only have 1 column. All other columns will be fill with "NULL AS" to 700 columns.

As you can see in my comment, 
1 column and 100000 rows: It takes 0.135 seconds 
700 column and 0 rows: It takes 0.084 seconds
700 column and 1000 rows: It takes 0.284 seconds
700 column and 10000 rows: It takes 1.705 seconds
700 column and 50000 rows: It takes 8.398 seconds
700 column and 100000 rows: It takes 16.16 seconds

It won't happen if it's 1 column with many rows or 0 row with many columns.
With many columns and many result rows, it's getting slower and slower (which is linear increasing trend).

**Comment by zellerh** [comment]
When I tried this on GPDB 6.0, I got a bit faster results

|rows|cols|wuboy0307's time|zellerh's time|time with limit clause|explain time on MacOS|
|---|---|---|---|---|---|
|100000|1|0.135|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|
|0|700|0.084|x|y|z|

**Pull request merged**
